<file name=index.html path=/Users/turtle/Workspace/ChendiDotLin.github.io/index.html>
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Chendi Lin</title>
    <style>
      .sticky-avatar {
        position: fixed;
        top: 10px;
        left: 10px;
        width: 100px;
        height: 100px;
        border-radius: 50%;
        transition: width 0.3s ease, height 0.3s ease;
        z-index: 1000;
      }

      .sticky-avatar.shrink {
        width: 50px;
        height: 50px;
      }
    </style>
</head>
<body>
    <img src="/img/profile2.PNG" class="sticky-avatar" alt="Avatar">
    <!-- Other content -->
    
    <script>
      window.addEventListener('scroll', function () {
        const avatar = document.querySelector('.sticky-avatar');
        if (window.scrollY > 50) {
          avatar.classList.add('shrink');
        } else {
          avatar.classList.remove('shrink');
        }
      });
    </script>
</body>
</html>
</file>
